//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.template
{
public sealed partial class Base_2 :  Bright.Config.BeanBase 
{
    public Base_2(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MyText_l10n_key = _buf.ReadString(); MyText = _buf.ReadString();
        PostInit();
    }

    public static Base_2 DeserializeBase_2(ByteBuf _buf)
    {
        return new template.Base_2(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 描述1
    /// </summary>
    public string MyText { get; private set; }
    public string MyText_l10n_key { get; }

    public const int __ID__ = 1109543512;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        MyText = translator(MyText_l10n_key, MyText);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MyText:" + MyText + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}