//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.template
{
   
public partial class TbBase_1
{
    private readonly Dictionary<int, template.Base_1> _dataMap;
    private readonly List<template.Base_1> _dataList;
    
    public TbBase_1(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, template.Base_1>();
        _dataList = new List<template.Base_1>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            template.Base_1 _v;
            _v = template.Base_1.DeserializeBase_1(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, template.Base_1> DataMap => _dataMap;
    public List<template.Base_1> DataList => _dataList;

    public template.Base_1 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public template.Base_1 Get(int key) => _dataMap[key];
    public template.Base_1 this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}