
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public abstract partial class ALocalizeConfig : Luban.BeanBase
{
    public ALocalizeConfig(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
    }

    public static ALocalizeConfig DeserializeALocalizeConfig(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "LocalizeConfig_CN": return new LocalizeConfig_CN(_buf);
            case "LocalizeConfig_EN": return new LocalizeConfig_EN(_buf);
            case "LocalizeConfig_TW": return new LocalizeConfig_TW(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string Key;
   

    public virtual void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "}";
    }
}

}
