
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class L10n : Luban.BeanBase
{
    public L10n(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
        { if(!_buf["zh"].IsString) { throw new SerializationException(); }  Zh = _buf["zh"]; }
    }

    public static L10n DeserializeL10n(JSONNode _buf)
    {
        return new L10n(_buf);
    }

    /// <summary>
    /// key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// en
    /// </summary>
    public readonly string En;
    /// <summary>
    /// zh
    /// </summary>
    public readonly string Zh;
   
    public const int __ID__ = 2312803;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "en:" + En + ","
        + "zh:" + Zh + ","
        + "}";
    }
}

}
