
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LocalizeConfig_TW : ALocalizeConfig
{
    public LocalizeConfig_TW(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["text_tw"].IsString) { throw new SerializationException(); }  TextTw = _buf["text_tw"]; }
    }

    public static LocalizeConfig_TW DeserializeLocalizeConfig_TW(JSONNode _buf)
    {
        return new LocalizeConfig_TW(_buf);
    }

    public readonly string TextTw;
   
    public const int __ID__ = 2049583223;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textTw:" + TextTw + ","
        + "}";
    }
}

}
