
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LocalizeConfig_TWCategory
{
    private readonly System.Collections.Generic.Dictionary<string, LocalizeConfig_TW> _dataMap;
    private readonly System.Collections.Generic.List<LocalizeConfig_TW> _dataList;
    
    public LocalizeConfig_TWCategory(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LocalizeConfig_TW>();
        _dataList = new System.Collections.Generic.List<LocalizeConfig_TW>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LocalizeConfig_TW _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LocalizeConfig_TW.DeserializeLocalizeConfig_TW(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LocalizeConfig_TW> DataMap => _dataMap;
    public System.Collections.Generic.List<LocalizeConfig_TW> DataList => _dataList;

    public LocalizeConfig_TW GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocalizeConfig_TW Get(string key) => _dataMap[key];
    public LocalizeConfig_TW this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
