
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LocalizeConfig_EN : ALocalizeConfig
{
    public LocalizeConfig_EN(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["text_en"].IsString) { throw new SerializationException(); }  TextEn = _buf["text_en"]; }
    }

    public static LocalizeConfig_EN DeserializeLocalizeConfig_EN(JSONNode _buf)
    {
        return new LocalizeConfig_EN(_buf);
    }

    public readonly string TextEn;
   
    public const int __ID__ = 2049582749;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textEn:" + TextEn + ","
        + "}";
    }
}

}
