
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LocalizeConfig_CNCategory
{
    private readonly System.Collections.Generic.Dictionary<string, LocalizeConfig_CN> _dataMap;
    private readonly System.Collections.Generic.List<LocalizeConfig_CN> _dataList;
    
    public LocalizeConfig_CNCategory(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LocalizeConfig_CN>();
        _dataList = new System.Collections.Generic.List<LocalizeConfig_CN>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LocalizeConfig_CN _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LocalizeConfig_CN.DeserializeLocalizeConfig_CN(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LocalizeConfig_CN> DataMap => _dataMap;
    public System.Collections.Generic.List<LocalizeConfig_CN> DataList => _dataList;

    public LocalizeConfig_CN GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocalizeConfig_CN Get(string key) => _dataMap[key];
    public LocalizeConfig_CN this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
