
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LocalizeConfig_CN : ALocalizeConfig
{
    public LocalizeConfig_CN(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["text_cn"].IsString) { throw new SerializationException(); }  TextCn = _buf["text_cn"]; }
    }

    public static LocalizeConfig_CN DeserializeLocalizeConfig_CN(JSONNode _buf)
    {
        return new LocalizeConfig_CN(_buf);
    }

    public readonly string TextCn;
   
    public const int __ID__ = 2049582687;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textCn:" + TextCn + ","
        + "}";
    }
}

}
