//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public template.TbBase_1 TbBase_1 {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TbBase_1 = new template.TbBase_1(loader("template_tbbase_1")); 
        tables.Add("template.TbBase_1", TbBase_1);

        PostInit();
        TbItem.Resolve(tables); 
        TbBase_1.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbBase_1.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}